/* This function was automatically generated by CasADi */#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) arc_solver_model_20_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "arc_solver/include/arc_solver.h"

#define PRINTF printf
arc_solver_FLOAT CASADI_PREFIX(sq)(arc_solver_FLOAT x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

arc_solver_FLOAT CASADI_PREFIX(sign)(arc_solver_FLOAT x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[] = {31, 1, 0, 31, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[] = {1, 8, 0, 1, 2, 3, 4, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
/* evaluate_stages */
int arc_solver_model_20(const arc_solver_FLOAT** arg, arc_solver_FLOAT** res) {
     arc_solver_FLOAT a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38;
         a0=arg[0] ? arg[0][2] : 0;
         a1=arg[1] ? arg[1][0] : 0;
  a1=(a0-a1);
         a2=sq(a1);
         a3=arg[1] ? arg[1][3] : 0;
  a2=(a3*a2);
         a4=arg[0] ? arg[0][3] : 0;
         a5=arg[1] ? arg[1][1] : 0;
  a5=(a4-a5);
         a6=sq(a5);
         a7=arg[1] ? arg[1][4] : 0;
  a6=(a7*a6);
  a2=(a2+a6);
  a6=arg[0] ? arg[0][5] : 0;
         a8=arg[1] ? arg[1][2] : 0;
  a8=(a6-a8);
         a9=sq(a8);
         a10=arg[1] ? arg[1][5] : 0;
  a9=(a10*a9);
  a2=(a2+a9);
  a9=arg[0] ? arg[0][6] : 0;
         a11=arg[0] ? arg[0][0] : 0;
  a9=(a9-a11);
         a12=sq(a9);
         a13=arg[1] ? arg[1][6] : 0;
  a12=(a13*a12);
  a2=(a2+a12);
  a12=arg[0] ? arg[0][7] : 0;
         a14=arg[0] ? arg[0][1] : 0;
  a12=(a12-a14);
         a15=sq(a12);
         a16=arg[1] ? arg[1][7] : 0;
  a15=(a16*a15);
  a2=(a2+a15);
  a15=sq(a11);
         a17=arg[1] ? arg[1][8] : 0;
  a15=(a17*a15);
  a2=(a2+a15);
  a15=sq(a14);
         a18=arg[1] ? arg[1][9] : 0;
  a15=(a18*a15);
  a2=(a2+a15);
  a15=arg[1] ? arg[1][11] : 0;
  a15=(a0-a15);
         a19=cos(a6);
         a20=2.3558500000000002e+00;
  a19=(a20*a19);
         a21=2.;
  a19=(a19/a21);
  a15=(a15+a19);
  a19=sq(a15);
         a22=arg[1] ? arg[1][12] : 0;
  a22=(a4-a22);
         a23=sin(a6);
  a23=(a20*a23);
  a23=(a23/a21);
  a22=(a22+a23);
  a23=sq(a22);
  a19=(a19+a23);
  a23=arg[1] ? arg[1][13] : 0;
         a24=4.0000000000000002e-01;
  a23=(a23+a24);
  a23=sq(a23);
  a19=(a19-a23);
  a19=(-a19);
  a19=exp(a19);
  a23=arg[1] ? arg[1][26] : 0;
         a25=(a23*a19);
  a2=(a2+a25);
  a25=arg[1] ? arg[1][14] : 0;
  a25=(a0-a25);
         a26=cos(a6);
  a26=(a20*a26);
  a26=(a26/a21);
  a25=(a25+a26);
  a26=sq(a25);
         a27=arg[1] ? arg[1][15] : 0;
  a27=(a4-a27);
         a28=sin(a6);
  a28=(a20*a28);
  a28=(a28/a21);
  a27=(a27+a28);
  a28=sq(a27);
  a26=(a26+a28);
  a28=arg[1] ? arg[1][16] : 0;
  a28=(a28+a24);
  a28=sq(a28);
  a26=(a26-a28);
  a26=(-a26);
  a26=exp(a26);
  a28=arg[1] ? arg[1][27] : 0;
         a29=(a28*a26);
  a2=(a2+a29);
  a29=arg[1] ? arg[1][17] : 0;
  a29=(a0-a29);
         a30=cos(a6);
  a30=(a20*a30);
  a30=(a30/a21);
  a29=(a29+a30);
  a30=sq(a29);
         a31=arg[1] ? arg[1][18] : 0;
  a31=(a4-a31);
         a32=sin(a6);
  a32=(a20*a32);
  a32=(a32/a21);
  a31=(a31+a32);
  a32=sq(a31);
  a30=(a30+a32);
  a32=arg[1] ? arg[1][19] : 0;
  a32=(a32+a24);
  a32=sq(a32);
  a30=(a30-a32);
  a30=(-a30);
  a30=exp(a30);
  a32=arg[1] ? arg[1][28] : 0;
         a33=(a32*a30);
  a2=(a2+a33);
  a33=arg[1] ? arg[1][20] : 0;
  a33=(a0-a33);
         a34=cos(a6);
  a34=(a20*a34);
  a34=(a34/a21);
  a33=(a33+a34);
  a34=sq(a33);
         a35=arg[1] ? arg[1][21] : 0;
  a35=(a4-a35);
         a36=sin(a6);
  a36=(a20*a36);
  a36=(a36/a21);
  a35=(a35+a36);
  a36=sq(a35);
  a34=(a34+a36);
  a36=arg[1] ? arg[1][22] : 0;
  a36=(a36+a24);
  a36=sq(a36);
  a34=(a34-a36);
  a34=(-a34);
  a34=exp(a34);
  a36=arg[1] ? arg[1][29] : 0;
         a37=(a36*a34);
  a2=(a2+a37);
  a37=arg[1] ? arg[1][23] : 0;
  a0=(a0-a37);
  a37=cos(a6);
  a37=(a20*a37);
  a37=(a37/a21);
  a0=(a0+a37);
  a37=sq(a0);
         a38=arg[1] ? arg[1][24] : 0;
  a4=(a4-a38);
  a38=sin(a6);
  a38=(a20*a38);
  a38=(a38/a21);
  a4=(a4+a38);
  a38=sq(a4);
  a37=(a37+a38);
  a38=arg[1] ? arg[1][25] : 0;
  a38=(a38+a24);
  a38=sq(a38);
  a37=(a37-a38);
  a37=(-a37);
  a37=exp(a37);
  a38=arg[1] ? arg[1][30] : 0;
  a24=(a38*a37);
  a2=(a2+a24);
  if (res[0]!=0) res[0][0]=a2;
  a11=(a11+a11);
  a11=(a11*a17);
  a9=(a9+a9);
  a9=(a9*a13);
  a11=(a11-a9);
  if (res[1]!=0) res[1][0]=a11;
  a14=(a14+a14);
  a14=(a14*a18);
  a12=(a12+a12);
  a12=(a12*a16);
  a14=(a14-a12);
  if (res[1]!=0) res[1][1]=a14;
  a1=(a1+a1);
  a1=(a1*a3);
  a0=(a0+a0);
  a37=(a37*a38);
  a0=(a0*a37);
  a33=(a33+a33);
  a34=(a34*a36);
  a33=(a33*a34);
  a36=(a0+a33);
  a29=(a29+a29);
  a30=(a30*a32);
  a29=(a29*a30);
  a36=(a36+a29);
  a25=(a25+a25);
  a26=(a26*a28);
  a25=(a25*a26);
  a36=(a36+a25);
  a15=(a15+a15);
  a19=(a19*a23);
  a15=(a15*a19);
  a36=(a36+a15);
  a1=(a1-a36);
  if (res[1]!=0) res[1][2]=a1;
  a5=(a5+a5);
  a5=(a5*a7);
  a4=(a4+a4);
  a4=(a4*a37);
  a35=(a35+a35);
  a35=(a35*a34);
  a34=(a4+a35);
  a31=(a31+a31);
  a31=(a31*a30);
  a34=(a34+a31);
  a27=(a27+a27);
  a27=(a27*a26);
  a34=(a34+a27);
  a22=(a22+a22);
  a22=(a22*a19);
  a34=(a34+a22);
  a5=(a5-a34);
  if (res[1]!=0) res[1][3]=a5;
  a5=5.0000000000000000e-01;
  a0=(a5*a0);
  a0=(a20*a0);
  a34=sin(a6);
  a34=(a34*a0);
  a4=(a5*a4);
  a4=(a20*a4);
  a0=cos(a6);
  a0=(a0*a4);
  a34=(a34-a0);
  a35=(a5*a35);
  a35=(a20*a35);
  a0=cos(a6);
  a0=(a0*a35);
  a34=(a34-a0);
  a33=(a5*a33);
  a33=(a20*a33);
  a0=sin(a6);
  a0=(a0*a33);
  a34=(a34+a0);
  a31=(a5*a31);
  a31=(a20*a31);
  a0=cos(a6);
  a0=(a0*a31);
  a34=(a34-a0);
  a29=(a5*a29);
  a29=(a20*a29);
  a0=sin(a6);
  a0=(a0*a29);
  a34=(a34+a0);
  a27=(a5*a27);
  a27=(a20*a27);
  a0=cos(a6);
  a0=(a0*a27);
  a34=(a34-a0);
  a25=(a5*a25);
  a25=(a20*a25);
  a0=sin(a6);
  a0=(a0*a25);
  a34=(a34+a0);
  a22=(a5*a22);
  a22=(a20*a22);
  a0=cos(a6);
  a0=(a0*a22);
  a34=(a34-a0);
  a5=(a5*a15);
  a20=(a20*a5);
  a6=sin(a6);
  a6=(a6*a20);
  a34=(a34+a6);
  a8=(a8+a8);
  a8=(a8*a10);
  a34=(a34+a8);
  if (res[1]!=0) res[1][4]=a34;
  if (res[1]!=0) res[1][5]=a9;
  if (res[1]!=0) res[1][6]=a12;
  return 0;
}

int arc_solver_model_20_init(int *f_type, int *n_in, int *n_out, int *sz_arg, int* sz_res) {
  *f_type = 1;
  *n_in = 2;
  *n_out = 2;
  *sz_arg = 2;
  *sz_res = 2;
  return 0;
}

int arc_solver_model_20_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row) {
  const int* s;
  switch (i) {
    case 0:
      s = s0; break;
    case 1:
      s = s1; break;
    case 2:
      s = s2; break;
    case 3:
      s = s3; break;
    default:
      return 1;
  }

  *nrow = s[0];
  *ncol = s[1];
  *colind = s + 2;
  *row = s + 2 + (*ncol + 1);
  return 0;
}

int arc_solver_model_20_work(int *sz_iw, int *sz_w) {
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 39;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
