/* This function was automatically generated by CasADi */#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) arc_solver_model_1_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "arc_solver/include/arc_solver.h"

#define PRINTF printf
arc_solver_FLOAT CASADI_PREFIX(sq)(arc_solver_FLOAT x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

arc_solver_FLOAT CASADI_PREFIX(sign)(arc_solver_FLOAT x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[] = {3, 1, 0, 3, 0, 1, 2};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[] = {1, 6, 0, 0, 0, 1, 2, 2, 2, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const int CASADI_PREFIX(s4)[] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s4 CASADI_PREFIX(s4)
static const int CASADI_PREFIX(s5)[] = {4, 6, 0, 4, 7, 8, 9, 13, 16, 0, 1, 2, 3, 0, 1, 3, 0, 1, 0, 1, 2, 3, 0, 1, 3};
#define s5 CASADI_PREFIX(s5)
/* evaluate_stages */
int arc_solver_model_1(const arc_solver_FLOAT** arg, arc_solver_FLOAT** res) {
     arc_solver_FLOAT a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36;
         a0=arg[0] ? arg[0][2] : 0;
         a1=arg[1] ? arg[1][0] : 0;
  a1=(a0-a1);
         a2=sq(a1);
         a3=arg[0] ? arg[0][3] : 0;
         a4=arg[1] ? arg[1][1] : 0;
  a4=(a3-a4);
         a5=sq(a4);
  a2=(a2+a5);
  if (res[0]!=0) res[0][0]=a2;
  a1=(a1+a1);
  if (res[1]!=0) res[1][0]=a1;
  a4=(a4+a4);
  if (res[1]!=0) res[1][1]=a4;
  a4=arg[0] ? arg[0][5] : 0;
  a1=cos(a4);
  a2=arg[0] ? arg[0][4] : 0;
  a5=(a2*a1);
         a6=5.0000000000000003e-02;
         a7=arg[0] ? arg[0][0] : 0;
         a8=(a6*a7);
  a8=(a2+a8);
         a9=arg[0] ? arg[0][1] : 0;
         a10=tan(a9);
         a11=(a10*a2);
         a12=2.;
  a11=(a11/a12);
         a13=(a6*a11);
  a13=(a4+a13);
         a14=cos(a13);
         a15=(a8*a14);
  a15=(a12*a15);
  a5=(a5+a15);
  a15=(a6*a7);
  a15=(a2+a15);
         a16=tan(a9);
         a17=(a16*a8);
         a18=(a17/a12);
  a18=(a6*a18);
  a18=(a4+a18);
         a19=cos(a18);
         a20=(a15*a19);
  a20=(a12*a20);
  a5=(a5+a20);
  a20=1.0000000000000001e-01;
         a21=(a20*a7);
  a21=(a2+a21);
         a22=tan(a9);
         a23=(a22*a15);
         a24=(a23/a12);
  a24=(a20*a24);
  a24=(a4+a24);
         a25=cos(a24);
         a26=(a21*a25);
  a5=(a5+a26);
  a26=1.6666666666666666e-02;
  a5=(a26*a5);
  a0=(a0+a5);
  if (res[2]!=0) res[2][0]=a0;
  a0=sin(a4);
  a5=(a2*a0);
         a27=sin(a13);
         a28=(a8*a27);
  a28=(a12*a28);
  a5=(a5+a28);
  a28=sin(a18);
         a29=(a15*a28);
  a29=(a12*a29);
  a5=(a5+a29);
  a29=sin(a24);
         a30=(a21*a29);
  a5=(a5+a30);
  a5=(a26*a5);
  a3=(a3+a5);
  if (res[2]!=0) res[2][1]=a3;
  a3=(a12*a7);
  a3=(a7+a3);
  a5=(a12*a7);
  a3=(a3+a5);
  a3=(a3+a7);
  a3=(a26*a3);
  a3=(a2+a3);
  if (res[2]!=0) res[2][2]=a3;
  a11=(a11+a17);
  a11=(a11+a23);
  a23=tan(a9);
  a17=(a23*a21);
  a17=(a17/a12);
  a11=(a11+a17);
  a11=(a26*a11);
  a11=(a4+a11);
  if (res[2]!=0) res[2][3]=a11;
  a11=(a6*a14);
  a11=(a12*a11);
  a17=(a6*a19);
  a3=(a6*a16);
  a7=5.0000000000000000e-01;
  a5=(a7*a3);
  a5=(a6*a5);
  a30=sin(a18);
         a31=(a30*a5);
  a31=(a15*a31);
  a17=(a17-a31);
  a17=(a12*a17);
  a11=(a11+a17);
  a17=(a20*a25);
  a31=(a6*a22);
         a32=(a7*a31);
  a32=(a20*a32);
         a33=sin(a24);
         a34=(a33*a32);
  a34=(a21*a34);
  a17=(a17-a34);
  a11=(a11+a17);
  a11=(a26*a11);
  if (res[3]!=0) res[3][0]=a11;
  a11=(a6*a27);
  a11=(a12*a11);
  a17=(a6*a28);
  a18=cos(a18);
  a5=(a18*a5);
  a5=(a15*a5);
  a17=(a17+a5);
  a17=(a12*a17);
  a11=(a11+a17);
  a17=(a20*a29);
  a24=cos(a24);
  a32=(a24*a32);
  a32=(a21*a32);
  a17=(a17+a32);
  a11=(a11+a17);
  a11=(a26*a11);
  if (res[3]!=0) res[3][1]=a11;
  if (res[3]!=0) res[3][2]=a20;
  a3=(a3+a31);
  a31=(a20*a23);
  a31=(a7*a31);
  a3=(a3+a31);
  a3=(a26*a3);
  if (res[3]!=0) res[3][3]=a3;
  a3=cos(a9);
  a3=sq(a3);
  a3=(a2/a3);
  a3=(a7*a3);
  a31=(a6*a3);
  a11=sin(a13);
  a17=(a11*a31);
  a17=(a8*a17);
  a17=(a12*a17);
  a32=cos(a9);
  a32=sq(a32);
  a32=(a8/a32);
  a5=(a7*a32);
  a5=(a6*a5);
  a34=(a30*a5);
  a34=(a15*a34);
  a34=(a12*a34);
  a17=(a17+a34);
  a34=cos(a9);
  a34=sq(a34);
  a34=(a15/a34);
         a35=(a7*a34);
  a35=(a20*a35);
         a36=(a33*a35);
  a36=(a21*a36);
  a17=(a17+a36);
  a17=(a26*a17);
  a17=(-a17);
  if (res[3]!=0) res[3][4]=a17;
  a13=cos(a13);
  a31=(a13*a31);
  a31=(a8*a31);
  a31=(a12*a31);
  a5=(a18*a5);
  a5=(a15*a5);
  a5=(a12*a5);
  a31=(a31+a5);
  a35=(a24*a35);
  a35=(a21*a35);
  a31=(a31+a35);
  a31=(a26*a31);
  if (res[3]!=0) res[3][5]=a31;
  a3=(a3+a32);
  a3=(a3+a34);
  a9=cos(a9);
  a9=sq(a9);
  a9=(a21/a9);
  a9=(a7*a9);
  a3=(a3+a9);
  a3=(a26*a3);
  if (res[3]!=0) res[3][6]=a3;
  a3=1.;
  if (res[3]!=0) res[3][7]=a3;
  if (res[3]!=0) res[3][8]=a3;
  a10=(a7*a10);
  a9=(a6*a10);
  a34=(a11*a9);
  a34=(a8*a34);
  a14=(a14-a34);
  a14=(a12*a14);
  a1=(a1+a14);
  a14=(a7*a16);
  a6=(a6*a14);
  a14=(a30*a6);
  a14=(a15*a14);
  a19=(a19-a14);
  a19=(a12*a19);
  a1=(a1+a19);
  a19=(a7*a22);
  a20=(a20*a19);
  a19=(a33*a20);
  a19=(a21*a19);
  a25=(a25-a19);
  a1=(a1+a25);
  a1=(a26*a1);
  if (res[3]!=0) res[3][9]=a1;
  a9=(a13*a9);
  a9=(a8*a9);
  a27=(a27+a9);
  a27=(a12*a27);
  a0=(a0+a27);
  a6=(a18*a6);
  a6=(a15*a6);
  a28=(a28+a6);
  a28=(a12*a28);
  a0=(a0+a28);
  a20=(a24*a20);
  a20=(a21*a20);
  a29=(a29+a20);
  a0=(a0+a29);
  a0=(a26*a0);
  if (res[3]!=0) res[3][10]=a0;
  if (res[3]!=0) res[3][11]=a3;
  a10=(a10+a16);
  a10=(a10+a22);
  a7=(a7*a23);
  a10=(a10+a7);
  a10=(a26*a10);
  if (res[3]!=0) res[3][12]=a10;
  a10=sin(a4);
  a10=(a2*a10);
  a11=(a8*a11);
  a11=(a12*a11);
  a10=(a10+a11);
  a30=(a15*a30);
  a30=(a12*a30);
  a10=(a10+a30);
  a33=(a21*a33);
  a10=(a10+a33);
  a10=(a26*a10);
  a10=(-a10);
  if (res[3]!=0) res[3][13]=a10;
  a4=cos(a4);
  a2=(a2*a4);
  a8=(a8*a13);
  a8=(a12*a8);
  a2=(a2+a8);
  a15=(a15*a18);
  a12=(a12*a15);
  a2=(a2+a12);
  a21=(a21*a24);
  a2=(a2+a21);
  a26=(a26*a2);
  if (res[3]!=0) res[3][14]=a26;
  if (res[3]!=0) res[3][15]=a3;
  return 0;
}

int arc_solver_model_1_init(int *f_type, int *n_in, int *n_out, int *sz_arg, int* sz_res) {
  *f_type = 1;
  *n_in = 2;
  *n_out = 4;
  *sz_arg = 2;
  *sz_res = 4;
  return 0;
}

int arc_solver_model_1_sparsity(int i, int *nrow, int *ncol, const int **colind, const int **row) {
  const int* s;
  switch (i) {
    case 0:
      s = s0; break;
    case 1:
      s = s1; break;
    case 2:
      s = s2; break;
    case 3:
      s = s3; break;
    case 4:
      s = s4; break;
    case 5:
      s = s5; break;
    default:
      return 1;
  }

  *nrow = s[0];
  *ncol = s[1];
  *colind = s + 2;
  *row = s + 2 + (*ncol + 1);
  return 0;
}

int arc_solver_model_1_work(int *sz_iw, int *sz_w) {
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 37;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
