% arc_solver - a fast interior point code generated by FORCES
%
%   OUTPUT = arc_solver(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.x0 - column vector of length 54
%       PARAMS.xinit - column vector of length 4
%       PARAMS.all_parameters - column vector of length 27
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.x1 - column vector of size 6
%       OUTPUT.x2 - column vector of size 6
%       OUTPUT.x3 - column vector of size 6
%       OUTPUT.x4 - column vector of size 6
%       OUTPUT.x5 - column vector of size 6
%       OUTPUT.x6 - column vector of size 6
%       OUTPUT.x7 - column vector of size 6
%       OUTPUT.x8 - column vector of size 6
%       OUTPUT.x9 - column vector of size 6
%
%   [OUTPUT, EXITFLAG] = arc_solver(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -6 - NaN or INF occured during evaluation of functions and derivatives. Please check your initial guess.
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = arc_solver(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.mu        - duality measure
%       INFO.solvetime - Time needed for solve (wall clock time)
%       INFO.fevalstime - Time needed for solve (wall clock time)
%
% See also COPYING
